### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by SelStefan** [lelandrichardson/react-image-magnifier#1]
Once when I require the module at the top of my app, I get this error:

```
ERROR in ./~/react-image-magnifier/src/ImageMagnifier.js
Module parse failed: C:\Users\...\app\node_modules\react-image-magnifier\src\ImageMagnifier.js Line 43: Un
expected token (
You may need an appropriate loader to handle this file type.
|     },
|
|     render () {
|         var props = this.props;
|         var halfSize = props.size / 2;
 @ ./~/react-image-magnifier/index.js 1:17-48
```

**Comment by bnchdrff** [comment]
@SelStefan see https://github.com/andreypopp/reactify/issues/20

**Comment by lelandrichardson** [comment]
@SelStefan as @bnchdrff points out, this is because the source file expects to be parsed by a JSX-aware parser.

This is probably not ideal, and I should have package.json's main entry point to a jsx-compiled file.

I'll fix this soon, and leave this image open until I do. You should be able to use the link @SelStefan provided in the mean time to fix your issues.

**Comment by SelStefan** [comment]
Problem solved. Thanks guys! :+1:

**Comment by aruna13** [comment]
Still facing the same issue, was this fixed?

**Comment by ghost** [comment]
Looks like this will never be fixed
